version: '3.8'

services:

    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - db
    db:
        image: postgres
        container_name: postgres
        volumes:
            - ./docker/postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: cheapsms_db
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root

    # Application Service
    app:
        container_name: cheapsms
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        working_dir: /var/www

