version: '3.8'

services:

    # Web Server Service
    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - db
    db:
        image: postgres
        volumes:
            - ./_docker/postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: sanctum_db
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root

    # Application Service
    app:
        build:
            context: .
            dockerfile: ./_docker/php/Dockerfile
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        working_dir: /var/www

