version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - '.:/var/www'
        ports:
            - "${APP_PORT:-80}:80"
        networks:
            - app
        restart: unless-stopped

    pgsql:
        image: 'postgres:15.2'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
        networks:
            - app

networks:
    app:
        driver: bridge

volumes:
    sail-pgsql:
        driver: local
